import { createApp } from 'vue'
import './styles/main.css'
import App from './App.vue'

const app = createApp(App)
app.mount('#app')

/**
 * Event delegation for dynamically rendered code block copy buttons.
 * These buttons are generated by useMarkdown and injected via v-html,
 * so we cannot use Vue's @click binding on them.
 */
const COPY_FEEDBACK_MS = 2000

document.addEventListener('click', (e: MouseEvent) => {
  const target = e.target as HTMLElement
  if (!target.classList.contains('code-block-copy')) return

  const encodedCode = target.getAttribute('data-code')
  if (!encodedCode) return

  const code = decodeURIComponent(encodedCode)
  navigator.clipboard
    .writeText(code)
    .then(() => {
      target.textContent = 'Copied!'
      setTimeout(() => {
        target.textContent = 'Copy'
      }, COPY_FEEDBACK_MS)
    })
    .catch(() => {
      target.textContent = 'Failed'
      setTimeout(() => {
        target.textContent = 'Copy'
      }, COPY_FEEDBACK_MS)
    })
})

