import { createApp } from 'vue'
import './styles/main.css'
import './styles/tokens-premium.css'
import './ui/styles.css'
import App from './App.vue'
import { getVsCodeApi } from './composables/useVSCode'

createApp(App).mount('#app')

/**
 * Event delegation for dynamically rendered code block action buttons.
 * These buttons are generated by useMarkdown and injected via v-html,
 * so we cannot use Vue's @click binding on them.
 */
const COPY_FEEDBACK_MS = 2000
const APPLY_FEEDBACK_MS = 1500

function findActionButton(target: HTMLElement, cls: string): HTMLButtonElement | null {
  return (target.classList.contains(cls)
    ? target
    : target.closest(`.${cls}`)) as HTMLButtonElement | null
}

document.addEventListener('click', (e: MouseEvent) => {
  const target = e.target as HTMLElement

  // --- Copy ---
  const copyBtn = findActionButton(target, 'code-block-copy')
  if (copyBtn) {
    const encodedCode = copyBtn.getAttribute('data-code')
    if (!encodedCode) return
    const code = decodeURIComponent(encodedCode)
    navigator.clipboard
      .writeText(code)
      .then(() => {
        copyBtn.textContent = 'Copied!'
        setTimeout(() => { copyBtn.textContent = 'Copy' }, COPY_FEEDBACK_MS)
      })
      .catch(() => {
        copyBtn.textContent = 'Failed'
        setTimeout(() => { copyBtn.textContent = 'Copy' }, COPY_FEEDBACK_MS)
      })
    return
  }

  // --- Apply (Cursor-style: triggers editor-side inline diff) ---
  const applyBtn = findActionButton(target, 'code-block-apply')
  if (applyBtn) {
    const encodedCode = applyBtn.getAttribute('data-code')
    if (!encodedCode) return
    const code = decodeURIComponent(encodedCode)
    const filename = applyBtn.getAttribute('data-filename')
      ? decodeURIComponent(applyBtn.getAttribute('data-filename') as string)
      : undefined
    const language = applyBtn.getAttribute('data-lang')
      ? decodeURIComponent(applyBtn.getAttribute('data-lang') as string)
      : undefined
    const lineRange = applyBtn.getAttribute('data-linerange') || undefined
    getVsCodeApi().postMessage({ type: 'applyEdit', code, filename, language, lineRange })

    const label = applyBtn.querySelector('span')
    if (label) {
      const original = label.textContent
      label.textContent = 'Applying…'
      applyBtn.setAttribute('disabled', 'true')
      setTimeout(() => {
        label.textContent = original ?? 'Apply'
        applyBtn.removeAttribute('disabled')
      }, APPLY_FEEDBACK_MS)
    }
  }
})
